### ISSUE TITLE
needles: option to output a figure of traversed brain locations per vector

### ISSUE THREAD

**Issue by nsteinme** [int-brain-lab/ibllib-matlab#3]
Something like this, but using acronyms rather than full names:

![image](https://user-images.githubusercontent.com/7590975/61469433-1892ff80-a977-11e9-8d24-2b259a7bf5c9.png)

**Comment by oliche** [comment]
And the reverse, which is from a brain location, lookup closest or recorded electrode

**Comment by nsteinme** [comment]
the forward part is done: the function is "plotTrajectory" and you can call plot_brain_loc method of an ElectrodeArray to do it, too.
